# .github/workflows/publish-npm.yml

name: 📦 Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish Package to npm
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: 📦 Install dependencies
        run: npm ci

      - name: ✅ Run tests
        run: npm test

      - name: 🏗️ Build package
        run: npm run build

      - name: ✍️ Add shebang to CLI entrypoint
        run: |
          FILE="build/index.js"
          SHEBANG='#!/usr/bin/env node'
          if ! head -n 1 "$FILE" | grep -q "$SHEBANG"; then
            echo "Injecting shebang into $FILE"
            (echo "$SHEBANG"; cat "$FILE") > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          else
            echo "Shebang already present."
          fi

      - name: 🔢 Set package.json version from tag
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=${TAG#v}
          echo "Setting package.json version to $VERSION"
          npm version "$VERSION" --no-git-tag-version

      - name: 🚀 Publish to npm
        run: |
          echo "Publishing version: ${{ github.event.release.tag_name }}"
          TAG="latest"
          if [[ "${{ github.event.release.tag_name }}" == *"beta"* ]]; then
            echo "Beta release detected."
            TAG="beta"
          fi
          npm publish --tag "$TAG"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}          